### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by kingnobro** [KeriYuu/Wakey-Wakey#1]
Well, I am not familiar with `npm`. But there are some mistakes in **How to Run** section (at least for me).
1. `cd wakey-wakey/src` → `cd Wakey-Wakey/src`
2. `node-sass` needs to match `Node`: https://blog.csdn.net/lwj_07/article/details/127845777
3. After start the frontend server in a new terminal, the backend terminal shows:
```python
Traceback (most recent call last):
  File "/home/name/anaconda3/envs/wakey/lib/python3.7/site-packages/flask/app.py", line 2552, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/name/anaconda3/envs/wakey/lib/python3.7/site-packages/flask/app.py", line 2532, in wsgi_app
    response = self.handle_exception(e)
  File "/home/name/anaconda3/envs/wakey/lib/python3.7/site-packages/flask_cors/extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/name/anaconda3/envs/wakey/lib/python3.7/site-packages/flask/app.py", line 2529, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/name/anaconda3/envs/wakey/lib/python3.7/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/name/anaconda3/envs/wakey/lib/python3.7/site-packages/flask_cors/extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/name/anaconda3/envs/wakey/lib/python3.7/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/name/anaconda3/envs/wakey/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "run.py", line 186, in _getCoordinatesKeypoints
    scale_new_coordinates = getTransCdrs(epsilon, scale_coordinate, sourceKeypoints)
  File "/home/name/Wakey-Wakey/src/backend/deformation/localTrans.py", line 12, in getTransCdrs
    V = keypoints[0] # 相对于第一帧
IndexError: index 0 is out of bounds for axis 0 with size 0
```
4. After clicking the arrow in the left panel, it shows: `TypeError: load() missing 1 required positional argument: 'Loader'`. Need to run `pip install pyyaml==5.4.1`
5. Again, after clicking the arrow in the left panel, it shows:
```python
Traceback (most recent call last):
  File "/home/name/anaconda3/envs/wakey/lib/python3.7/site-packages/flask/app.py", line 2552, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/name/anaconda3/envs/wakey/lib/python3.7/site-packages/flask/app.py", line 2532, in wsgi_app
    response = self.handle_exception(e)
  File "/home/name/anaconda3/envs/wakey/lib/python3.7/site-packages/flask_cors/extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/name/anaconda3/envs/wakey/lib/python3.7/site-packages/flask/app.py", line 2529, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/name/anaconda3/envs/wakey/lib/python3.7/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/name/anaconda3/envs/wakey/lib/python3.7/site-packages/flask_cors/extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/name/anaconda3/envs/wakey/lib/python3.7/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/name/anaconda3/envs/wakey/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "run.py", line 79, in _getTextandGenerate
    fps = generate(opt, False, None, None)
  File "/home/name/Wakey-Wakey/src/backend/models/demo.py", line 134, in generate
    generator, kp_detector = load_checkpoints(config_path=opt['config'], checkpoint_path=opt['checkpoint'], cpu=opt['cpu'])
  File "/home/name/Wakey-Wakey/src/backend/models/demo.py", line 44, in load_checkpoints
    checkpoint = torch.load(checkpoint_path, map_location=torch.device('cpu'))
  File "/home/name/anaconda3/envs/wakey/lib/python3.7/site-packages/torch/serialization.py", line 367, in load
    return _load(f, map_location, pickle_module)
  File "/home/name/anaconda3/envs/wakey/lib/python3.7/site-packages/torch/serialization.py", line 528, in _load
    magic_number = pickle_module.load(f)
_pickle.UnpicklingError: invalid load key, '<'.
```

I don't know how to resolve the last problem. Do you have any idea? Thanks.

**Comment by kingnobro** [comment]
I solved it. `wget https://disk.yandex.com/d/lEw8uRm140L_eQ/mgif-cpk.pth.tar` will get a text file. So I manually download the `mgif-cpk.pth.tar` and put it to the `/models`.

**Comment by shellywhen** [comment]
Thank you for your feedback. We have updated the instructions of the repo.
